<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-D886HJ1" failures="0" tests="2" name="Test_Scripts.Admin_Login" time="4.412" errors="1" timestamp="2025-04-30T15:23:17 IST" skipped="0">
  <testcase classname="Test_Scripts.Admin_Login" name="AdminLogin_Test" time="4.225"/>
  <system-out/>
  <testcase classname="Test_Scripts.Admin_Login" name="TearDown" time="0.187">
    <error message="Cannot attach file &quot;C:\Users\Dinesh\git\Jenkins_Project/Reports/Automation_Report.html&quot;" type="org.apache.commons.mail.EmailException">
      <![CDATA[org.apache.commons.mail.EmailException: Cannot attach file "C:\Users\Dinesh\git\Jenkins_Project/Reports/Automation_Report.html"
at org.apache.commons.mail.MultiPartEmail.attach(MultiPartEmail.java:333)
at Base_Package.Java_Mail.sendmail(Java_Mail.java:41)
at Base_Package.Base_Class.TearDown(Base_Class.java:142)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:65)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:381)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:319)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:396)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.io.IOException: "C:\Users\Dinesh\git\Jenkins_Project/Reports/Automation_Report.html" does not exist
at org.apache.commons.mail.MultiPartEmail.attach(MultiPartEmail.java:322)
... 19 more
]]>
    </error>
  </testcase> <!-- TearDown -->
  <system-out/>
</testsuite> <!-- Test_Scripts.Admin_Login -->
